CREATE TABLE "POR_POSTS" (
	"POS_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"POS_SLUG" varchar(128) NOT NULL,
	"POS_TITLE" varchar(255) NOT NULL,
	"POS_DESCRIPTION" varchar(500) NOT NULL,
	"POS_CONTENT" text NOT NULL,
	"POS_PUBLISHED" boolean DEFAULT false NOT NULL,
	"USR_ID" uuid NOT NULL,
	"POS_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"POS_UPDATED_AT" timestamp DEFAULT now(),
	"POS_PUBLISHED_AT" timestamp,
	CONSTRAINT "POR_POSTS_POS_SLUG_unique" UNIQUE("POS_SLUG")
);
--> statement-breakpoint
CREATE TABLE "POR_POSTS_TAGS" (
	"POS_ID" uuid NOT NULL,
	"TAG_ID" uuid NOT NULL,
	CONSTRAINT "POR_POSTS_TAGS_POS_ID_TAG_ID_pk" PRIMARY KEY("POS_ID","TAG_ID")
);
--> statement-breakpoint
CREATE TABLE "POR_PROJECTS" (
	"PRJ_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"PRJ_SLUG" varchar(128) NOT NULL,
	"PRJ_TITLE" varchar(255) NOT NULL,
	"PRJ_DESCRIPTION" text NOT NULL,
	"PRJ_LINK" varchar(255),
	"PRJ_GITHUB" varchar(255),
	"PRJ_IMAGE" varchar(255),
	"PRJ_FEATURED" boolean DEFAULT false NOT NULL,
	"PRJ_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"USR_ID" uuid NOT NULL,
	"PRJ_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"PRJ_UPDATED_AT" timestamp DEFAULT now(),
	CONSTRAINT "POR_PROJECTS_PRJ_SLUG_unique" UNIQUE("PRJ_SLUG")
);
--> statement-breakpoint
CREATE TABLE "POR_PROJECTS_TECHNOLOGIES" (
	"PRJ_ID" uuid NOT NULL,
	"TEC_ID" uuid NOT NULL,
	CONSTRAINT "POR_PROJECTS_TECHNOLOGIES_PRJ_ID_TEC_ID_pk" PRIMARY KEY("PRJ_ID","TEC_ID")
);
--> statement-breakpoint
CREATE TABLE "POR_SESSIONS" (
	"SES_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"USR_ID" uuid NOT NULL,
	"SES_TOKEN" varchar(255) NOT NULL,
	"SES_EXPIRES_AT" timestamp NOT NULL,
	"SES_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "POR_SESSIONS_SES_TOKEN_unique" UNIQUE("SES_TOKEN")
);
--> statement-breakpoint
CREATE TABLE "POR_TAGS" (
	"TAG_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"TAG_NAME" varchar(64) NOT NULL,
	"TAG_SLUG" varchar(64) NOT NULL,
	"TAG_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "POR_TAGS_TAG_NAME_unique" UNIQUE("TAG_NAME"),
	CONSTRAINT "POR_TAGS_TAG_SLUG_unique" UNIQUE("TAG_SLUG")
);
--> statement-breakpoint
CREATE TABLE "POR_TECHNOLOGIES" (
	"TEC_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"TEC_NAME" varchar(64) NOT NULL,
	"TEC_SLUG" varchar(64) NOT NULL,
	"TEC_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "POR_TECHNOLOGIES_TEC_NAME_unique" UNIQUE("TEC_NAME"),
	CONSTRAINT "POR_TECHNOLOGIES_TEC_SLUG_unique" UNIQUE("TEC_SLUG")
);
--> statement-breakpoint
CREATE TABLE "POR_USERS" (
	"USR_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"USR_EMAIL" varchar(255) NOT NULL,
	"USR_PASSWORD_HASH" varchar(255) NOT NULL,
	"USR_NAME" varchar(64) NOT NULL,
	"USR_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"USR_UPDATED_AT" timestamp DEFAULT now(),
	CONSTRAINT "POR_USERS_USR_EMAIL_unique" UNIQUE("USR_EMAIL")
);
--> statement-breakpoint
ALTER TABLE "POR_POSTS" ADD CONSTRAINT "POR_POSTS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_POSTS_TAGS" ADD CONSTRAINT "POR_POSTS_TAGS_POS_ID_POR_POSTS_POS_ID_fk" FOREIGN KEY ("POS_ID") REFERENCES "public"."POR_POSTS"("POS_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_POSTS_TAGS" ADD CONSTRAINT "POR_POSTS_TAGS_TAG_ID_POR_TAGS_TAG_ID_fk" FOREIGN KEY ("TAG_ID") REFERENCES "public"."POR_TAGS"("TAG_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_PROJECTS" ADD CONSTRAINT "POR_PROJECTS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_PROJECTS_TECHNOLOGIES" ADD CONSTRAINT "POR_PROJECTS_TECHNOLOGIES_PRJ_ID_POR_PROJECTS_PRJ_ID_fk" FOREIGN KEY ("PRJ_ID") REFERENCES "public"."POR_PROJECTS"("PRJ_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_PROJECTS_TECHNOLOGIES" ADD CONSTRAINT "POR_PROJECTS_TECHNOLOGIES_TEC_ID_POR_TECHNOLOGIES_TEC_ID_fk" FOREIGN KEY ("TEC_ID") REFERENCES "public"."POR_TECHNOLOGIES"("TEC_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_SESSIONS" ADD CONSTRAINT "POR_SESSIONS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE cascade ON UPDATE no action;