CREATE TABLE "POR_EXPERIENCES" (
	"EXP_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"EXP_COMPANY" jsonb NOT NULL,
	"EXP_ROLE" jsonb NOT NULL,
	"EXP_DESCRIPTION" jsonb NOT NULL,
	"EXP_TYPE" varchar(20) NOT NULL,
	"EXP_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"EXP_START_DATE" timestamp NOT NULL,
	"EXP_END_DATE" timestamp,
	"EXP_COMPANY_URL" varchar(255),
	"EXP_LOGO" varchar(255),
	"USR_ID" uuid NOT NULL,
	"EXP_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"EXP_UPDATED_AT" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "POR_EXPERIENCES_TECHNOLOGIES" (
	"EXP_ID" uuid NOT NULL,
	"TEC_ID" uuid NOT NULL,
	CONSTRAINT "POR_EXPERIENCES_TECHNOLOGIES_EXP_ID_TEC_ID_pk" PRIMARY KEY("EXP_ID","TEC_ID")
);
--> statement-breakpoint
ALTER TABLE "POR_TECHNOLOGIES" DROP CONSTRAINT "POR_TECHNOLOGIES_TEC_NAME_unique";--> statement-breakpoint
ALTER TABLE "POR_POSTS" ALTER COLUMN "POS_TITLE" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_POSTS" ALTER COLUMN "POS_DESCRIPTION" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_POSTS" ALTER COLUMN "POS_CONTENT" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_PROJECTS" ALTER COLUMN "PRJ_TITLE" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_PROJECTS" ALTER COLUMN "PRJ_DESCRIPTION" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_TECHNOLOGIES" ALTER COLUMN "TEC_NAME" SET DATA TYPE jsonb;--> statement-breakpoint
ALTER TABLE "POR_EXPERIENCES" ADD CONSTRAINT "POR_EXPERIENCES_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_EXPERIENCES_TECHNOLOGIES" ADD CONSTRAINT "POR_EXPERIENCES_TECHNOLOGIES_EXP_ID_POR_EXPERIENCES_EXP_ID_fk" FOREIGN KEY ("EXP_ID") REFERENCES "public"."POR_EXPERIENCES"("EXP_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_EXPERIENCES_TECHNOLOGIES" ADD CONSTRAINT "POR_EXPERIENCES_TECHNOLOGIES_TEC_ID_POR_TECHNOLOGIES_TEC_ID_fk" FOREIGN KEY ("TEC_ID") REFERENCES "public"."POR_TECHNOLOGIES"("TEC_ID") ON DELETE cascade ON UPDATE no action;