CREATE TABLE "POR_SKILLS" (
	"SKI_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"SKI_NAME" jsonb NOT NULL,
	"SKI_CONTEXT" jsonb NOT NULL,
	"SKI_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"CAT_ID" uuid NOT NULL,
	"USR_ID" uuid NOT NULL,
	"SKI_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"SKI_UPDATED_AT" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "POR_SKILL_CATEGORIES" (
	"CAT_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"CAT_NAME" jsonb NOT NULL,
	"CAT_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"USR_ID" uuid NOT NULL,
	"CAT_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"CAT_UPDATED_AT" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "POR_SKILLS" ADD CONSTRAINT "POR_SKILLS_CAT_ID_POR_SKILL_CATEGORIES_CAT_ID_fk" FOREIGN KEY ("CAT_ID") REFERENCES "public"."POR_SKILL_CATEGORIES"("CAT_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_SKILLS" ADD CONSTRAINT "POR_SKILLS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_SKILL_CATEGORIES" ADD CONSTRAINT "POR_SKILL_CATEGORIES_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;