CREATE TABLE "POR_PASSIONS" (
	"PAS_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"PAS_TITLE" jsonb NOT NULL,
	"PAS_DESCRIPTION" jsonb NOT NULL,
	"PAS_ICON" varchar(50) NOT NULL,
	"PAS_IMAGE" varchar(255),
	"PAS_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"USR_ID" uuid NOT NULL,
	"PAS_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"PAS_UPDATED_AT" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "POR_PASSIONS_SOFT_SKILLS" (
	"PAS_ID" uuid NOT NULL,
	"SSK_ID" uuid NOT NULL,
	CONSTRAINT "POR_PASSIONS_SOFT_SKILLS_PAS_ID_SSK_ID_pk" PRIMARY KEY("PAS_ID","SSK_ID")
);
--> statement-breakpoint
CREATE TABLE "POR_SOFT_SKILLS" (
	"SSK_ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"SSK_NAME" jsonb NOT NULL,
	"SSK_DESCRIPTION" jsonb NOT NULL,
	"SSK_ICON" varchar(50) NOT NULL,
	"SSK_ORDER" varchar(10) DEFAULT '0' NOT NULL,
	"USR_ID" uuid NOT NULL,
	"SSK_CREATED_AT" timestamp DEFAULT now() NOT NULL,
	"SSK_UPDATED_AT" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "POR_PASSIONS" ADD CONSTRAINT "POR_PASSIONS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_PASSIONS_SOFT_SKILLS" ADD CONSTRAINT "POR_PASSIONS_SOFT_SKILLS_PAS_ID_POR_PASSIONS_PAS_ID_fk" FOREIGN KEY ("PAS_ID") REFERENCES "public"."POR_PASSIONS"("PAS_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_PASSIONS_SOFT_SKILLS" ADD CONSTRAINT "POR_PASSIONS_SOFT_SKILLS_SSK_ID_POR_SOFT_SKILLS_SSK_ID_fk" FOREIGN KEY ("SSK_ID") REFERENCES "public"."POR_SOFT_SKILLS"("SSK_ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "POR_SOFT_SKILLS" ADD CONSTRAINT "POR_SOFT_SKILLS_USR_ID_POR_USERS_USR_ID_fk" FOREIGN KEY ("USR_ID") REFERENCES "public"."POR_USERS"("USR_ID") ON DELETE no action ON UPDATE no action;